### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elasticsearch-specification#93]
As per #92 if the `DictionaryDecompounderTokenFilter` is included as part of the `TokenFilter` type, it causes the following exception. Once this issue is fixed, it can be uncommented from the `TokenFilter` in the `TokenFilterBase.ts` file.

```
/home/stevejgordon/elastic-client-generator/specification/src/specification/type-reader.ts:268
    const args: ts.Node[] = t.typeArguments.map(n => n as ts.Node)
                                            ^
TypeError: Cannot read property 'map' of undefined
    at InterfaceVisitor.createDictionary (/home/stevejgordon/elastic-client-generator/specification/src/specification/type-reader.ts:268:45)
    at InterfaceVisitor.visitTypeReference (/home/stevejgordon/elastic-client-generator/specification/src/specification/type-reader.ts:247:103)
    at InterfaceVisitor.visitTypeNode (/home/stevejgordon/elastic-client-generator/specification/src/specification/type-reader.ts:197:54)
    at /home/stevejgordon/elastic-client-generator/specification/src/specification/type-reader.ts:215:59
    at Array.map (<anonymous>)
    at InterfaceVisitor.visitUnionType (/home/stevejgordon/elastic-client-generator/specification/src/specification/type-reader.ts:215:42)
    at InterfaceVisitor.visitTypeNode (/home/stevejgordon/elastic-client-generator/specification/src/specification/type-reader.ts:203:49)
    at InterfaceVisitor.visit (/home/stevejgordon/elastic-client-generator/specification/src/specification/type-reader.ts:73:32)
    at TypeReader.visit (/home/stevejgordon/elastic-client-generator/specification/src/specification/type-reader.ts:354:33)
    at /home/stevejgordon/elastic-client-generator/specification/src/specification/type-reader.ts:358:56
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elasticsearch-client-specification@0.0.1 generate-schema: `ts-node src/metamodel_generate.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elasticsearch-client-specification@0.0.1 generate-schema script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/stevejgordon/.npm/_logs/2021-01-26T01_17_25_913Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elasticsearch-client-specification@0.0.1 compile:canonical-json: `npm run generate-schema --prefix specification`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elasticsearch-client-specification@0.0.1 compile:canonical-json script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/stevejgordon/.npm/_logs/2021-01-26T01_17_25_930Z-debug.log
```

**Comment by philkra** [comment]
@stevejgordon , is this issue still valid?
